services:
  raid_scheduler:
    container_name: raid-scheduler-service
    image: server:5000/raidschedulerbot:latest
    ports:
      - '8081:8080'
  mongodb:
    container_name: mongodb
    image: mongo:8.0.5
    ports:
      - '27017:27017'
    volumes:
      - data:/data
volumes:
  data : {}
networks:
  default:
    name: bot_net
