spring:
  data:
    mongodb:
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:mongodb}
      database: ${MONGODB_DB:d2RaidScheduler}
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    favicon:
      enabled: false

discord:
  token: ${DISCORD_TOKEN}
  botId: ${DISCORD_BOT_ID} # 1173022493229990008

d2scheduler:
  reminder:
    offset: ${REMINDER_OFFSET:1800000} # in milliseconds